#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrototipoV1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bd_bodega")]
	public partial class DatosBodegaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertPrecio(Precio instance);
    partial void UpdatePrecio(Precio instance);
    partial void DeletePrecio(Precio instance);
    partial void InsertImpuesto(Impuesto instance);
    partial void UpdateImpuesto(Impuesto instance);
    partial void DeleteImpuesto(Impuesto instance);
    #endregion
		
		public DatosBodegaDataContext() : 
				base(global::PrototipoV1.Properties.Settings.Default.bd_bodegaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DatosBodegaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosBodegaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosBodegaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatosBodegaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Precio> Precio
		{
			get
			{
				return this.GetTable<Precio>();
			}
		}
		
		public System.Data.Linq.Table<Impuesto> Impuesto
		{
			get
			{
				return this.GetTable<Impuesto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigo;
		
		private string _Descripcion;
		
		private string _Nombre;
		
		private double _Precio;
		
		private string _Tipo;
		
		private System.Nullable<int> _Unidades;
		
		private string _Medida;
		
		private string _Categoria;
		
		private string _Estado;
		
		private string _ultVenta;
		
		private EntitySet<Precio> _Precio1;
		
		private EntitySet<Impuesto> _Impuesto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoChanging(int value);
    partial void OnCodigoChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPrecioChanging(double value);
    partial void OnPrecioChanged();
    partial void OnTipoChanging(string value);
    partial void OnTipoChanged();
    partial void OnUnidadesChanging(System.Nullable<int> value);
    partial void OnUnidadesChanged();
    partial void OnMedidaChanging(string value);
    partial void OnMedidaChanged();
    partial void OnCategoriaChanging(string value);
    partial void OnCategoriaChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnultVentaChanging(string value);
    partial void OnultVentaChanged();
    #endregion
		
		public Producto()
		{
			this._Precio1 = new EntitySet<Precio>(new Action<Precio>(this.attach_Precio1), new Action<Precio>(this.detach_Precio1));
			this._Impuesto = new EntitySet<Impuesto>(new Action<Impuesto>(this.attach_Impuesto), new Action<Impuesto>(this.detach_Impuesto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(255)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Float NOT NULL")]
		public double Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo", DbType="VarChar(20)")]
		public string Tipo
		{
			get
			{
				return this._Tipo;
			}
			set
			{
				if ((this._Tipo != value))
				{
					this.OnTipoChanging(value);
					this.SendPropertyChanging();
					this._Tipo = value;
					this.SendPropertyChanged("Tipo");
					this.OnTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Unidades", DbType="Int")]
		public System.Nullable<int> Unidades
		{
			get
			{
				return this._Unidades;
			}
			set
			{
				if ((this._Unidades != value))
				{
					this.OnUnidadesChanging(value);
					this.SendPropertyChanging();
					this._Unidades = value;
					this.SendPropertyChanged("Unidades");
					this.OnUnidadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medida", DbType="VarChar(20)")]
		public string Medida
		{
			get
			{
				return this._Medida;
			}
			set
			{
				if ((this._Medida != value))
				{
					this.OnMedidaChanging(value);
					this.SendPropertyChanging();
					this._Medida = value;
					this.SendPropertyChanged("Medida");
					this.OnMedidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="VarChar(20)")]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this.OnCategoriaChanging(value);
					this.SendPropertyChanging();
					this._Categoria = value;
					this.SendPropertyChanged("Categoria");
					this.OnCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20)")]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ultVenta", DbType="VarChar(20)")]
		public string ultVenta
		{
			get
			{
				return this._ultVenta;
			}
			set
			{
				if ((this._ultVenta != value))
				{
					this.OnultVentaChanging(value);
					this.SendPropertyChanging();
					this._ultVenta = value;
					this.SendPropertyChanged("ultVenta");
					this.OnultVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Precio", Storage="_Precio1", ThisKey="Codigo", OtherKey="Codigo")]
		public EntitySet<Precio> Precio1
		{
			get
			{
				return this._Precio1;
			}
			set
			{
				this._Precio1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Impuesto", Storage="_Impuesto", ThisKey="Codigo", OtherKey="Codigo")]
		public EntitySet<Impuesto> Impuesto
		{
			get
			{
				return this._Impuesto;
			}
			set
			{
				this._Impuesto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Precio1(Precio entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Precio1(Precio entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Impuesto(Impuesto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Impuesto(Impuesto entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Precio")]
	public partial class Precio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_precio;
		
		private System.Nullable<int> _Codigo;
		
		private System.Nullable<double> _precio1;
		
		private System.Nullable<double> _precio2;
		
		private System.Nullable<double> _precio3;
		
		private System.Nullable<double> _precio4;
		
		private System.Nullable<double> _precio_unidad;
		
		private System.Nullable<double> _precioUS;
		
		private string _venta_contiene;
		
		private string _compra_contiene;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_precioChanging(int value);
    partial void Onid_precioChanged();
    partial void OnCodigoChanging(System.Nullable<int> value);
    partial void OnCodigoChanged();
    partial void Onprecio1Changing(System.Nullable<double> value);
    partial void Onprecio1Changed();
    partial void Onprecio2Changing(System.Nullable<double> value);
    partial void Onprecio2Changed();
    partial void Onprecio3Changing(System.Nullable<double> value);
    partial void Onprecio3Changed();
    partial void Onprecio4Changing(System.Nullable<double> value);
    partial void Onprecio4Changed();
    partial void Onprecio_unidadChanging(System.Nullable<double> value);
    partial void Onprecio_unidadChanged();
    partial void OnprecioUSChanging(System.Nullable<double> value);
    partial void OnprecioUSChanged();
    partial void Onventa_contieneChanging(string value);
    partial void Onventa_contieneChanged();
    partial void Oncompra_contieneChanging(string value);
    partial void Oncompra_contieneChanged();
    #endregion
		
		public Precio()
		{
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_precio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_precio
		{
			get
			{
				return this._id_precio;
			}
			set
			{
				if ((this._id_precio != value))
				{
					this.Onid_precioChanging(value);
					this.SendPropertyChanging();
					this._id_precio = value;
					this.SendPropertyChanged("id_precio");
					this.Onid_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int")]
		public System.Nullable<int> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio1", DbType="Float")]
		public System.Nullable<double> precio1
		{
			get
			{
				return this._precio1;
			}
			set
			{
				if ((this._precio1 != value))
				{
					this.Onprecio1Changing(value);
					this.SendPropertyChanging();
					this._precio1 = value;
					this.SendPropertyChanged("precio1");
					this.Onprecio1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio2", DbType="Float")]
		public System.Nullable<double> precio2
		{
			get
			{
				return this._precio2;
			}
			set
			{
				if ((this._precio2 != value))
				{
					this.Onprecio2Changing(value);
					this.SendPropertyChanging();
					this._precio2 = value;
					this.SendPropertyChanged("precio2");
					this.Onprecio2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio3", DbType="Float")]
		public System.Nullable<double> precio3
		{
			get
			{
				return this._precio3;
			}
			set
			{
				if ((this._precio3 != value))
				{
					this.Onprecio3Changing(value);
					this.SendPropertyChanging();
					this._precio3 = value;
					this.SendPropertyChanged("precio3");
					this.Onprecio3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio4", DbType="Float")]
		public System.Nullable<double> precio4
		{
			get
			{
				return this._precio4;
			}
			set
			{
				if ((this._precio4 != value))
				{
					this.Onprecio4Changing(value);
					this.SendPropertyChanging();
					this._precio4 = value;
					this.SendPropertyChanged("precio4");
					this.Onprecio4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precio_unidad", DbType="Float")]
		public System.Nullable<double> precio_unidad
		{
			get
			{
				return this._precio_unidad;
			}
			set
			{
				if ((this._precio_unidad != value))
				{
					this.Onprecio_unidadChanging(value);
					this.SendPropertyChanging();
					this._precio_unidad = value;
					this.SendPropertyChanged("precio_unidad");
					this.Onprecio_unidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioUS", DbType="Float")]
		public System.Nullable<double> precioUS
		{
			get
			{
				return this._precioUS;
			}
			set
			{
				if ((this._precioUS != value))
				{
					this.OnprecioUSChanging(value);
					this.SendPropertyChanging();
					this._precioUS = value;
					this.SendPropertyChanged("precioUS");
					this.OnprecioUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venta_contiene", DbType="VarChar(20)")]
		public string venta_contiene
		{
			get
			{
				return this._venta_contiene;
			}
			set
			{
				if ((this._venta_contiene != value))
				{
					this.Onventa_contieneChanging(value);
					this.SendPropertyChanging();
					this._venta_contiene = value;
					this.SendPropertyChanged("venta_contiene");
					this.Onventa_contieneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compra_contiene", DbType="VarChar(20)")]
		public string compra_contiene
		{
			get
			{
				return this._compra_contiene;
			}
			set
			{
				if ((this._compra_contiene != value))
				{
					this.Oncompra_contieneChanging(value);
					this.SendPropertyChanging();
					this._compra_contiene = value;
					this.SendPropertyChanged("compra_contiene");
					this.Oncompra_contieneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Precio", Storage="_Producto", ThisKey="Codigo", OtherKey="Codigo", IsForeignKey=true, DeleteRule="CASCADE")]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Precio1.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Precio1.Add(this);
						this._Codigo = value.Codigo;
					}
					else
					{
						this._Codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Impuesto")]
	public partial class Impuesto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_impuesto;
		
		private System.Nullable<int> _Codigo;
		
		private System.Nullable<double> _impuesto1;
		
		private System.Nullable<double> _impuesto2;
		
		private System.Nullable<double> _impuesto3;
		
		private System.Nullable<double> _impuesto4;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_impuestoChanging(int value);
    partial void Onid_impuestoChanged();
    partial void OnCodigoChanging(System.Nullable<int> value);
    partial void OnCodigoChanged();
    partial void Onimpuesto1Changing(System.Nullable<double> value);
    partial void Onimpuesto1Changed();
    partial void Onimpuesto2Changing(System.Nullable<double> value);
    partial void Onimpuesto2Changed();
    partial void Onimpuesto3Changing(System.Nullable<double> value);
    partial void Onimpuesto3Changed();
    partial void Onimpuesto4Changing(System.Nullable<double> value);
    partial void Onimpuesto4Changed();
    #endregion
		
		public Impuesto()
		{
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_impuesto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_impuesto
		{
			get
			{
				return this._id_impuesto;
			}
			set
			{
				if ((this._id_impuesto != value))
				{
					this.Onid_impuestoChanging(value);
					this.SendPropertyChanging();
					this._id_impuesto = value;
					this.SendPropertyChanged("id_impuesto");
					this.Onid_impuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int")]
		public System.Nullable<int> Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impuesto1", DbType="Float")]
		public System.Nullable<double> impuesto1
		{
			get
			{
				return this._impuesto1;
			}
			set
			{
				if ((this._impuesto1 != value))
				{
					this.Onimpuesto1Changing(value);
					this.SendPropertyChanging();
					this._impuesto1 = value;
					this.SendPropertyChanged("impuesto1");
					this.Onimpuesto1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impuesto2", DbType="Float")]
		public System.Nullable<double> impuesto2
		{
			get
			{
				return this._impuesto2;
			}
			set
			{
				if ((this._impuesto2 != value))
				{
					this.Onimpuesto2Changing(value);
					this.SendPropertyChanging();
					this._impuesto2 = value;
					this.SendPropertyChanged("impuesto2");
					this.Onimpuesto2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impuesto3", DbType="Float")]
		public System.Nullable<double> impuesto3
		{
			get
			{
				return this._impuesto3;
			}
			set
			{
				if ((this._impuesto3 != value))
				{
					this.Onimpuesto3Changing(value);
					this.SendPropertyChanging();
					this._impuesto3 = value;
					this.SendPropertyChanged("impuesto3");
					this.Onimpuesto3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_impuesto4", DbType="Float")]
		public System.Nullable<double> impuesto4
		{
			get
			{
				return this._impuesto4;
			}
			set
			{
				if ((this._impuesto4 != value))
				{
					this.Onimpuesto4Changing(value);
					this.SendPropertyChanging();
					this._impuesto4 = value;
					this.SendPropertyChanged("impuesto4");
					this.Onimpuesto4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Impuesto", Storage="_Producto", ThisKey="Codigo", OtherKey="Codigo", IsForeignKey=true, DeleteRule="CASCADE")]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Impuesto.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Impuesto.Add(this);
						this._Codigo = value.Codigo;
					}
					else
					{
						this._Codigo = default(Nullable<int>);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
